spring.datasource.url=jdbc:postgresql://dpg-d78dc34hg0os73dhv8hg-a.singapore-postgres.render.com:5432/hostel_db_gxpy?sslmode=require
spring.datasource.username=hostel_db_gxpy_user
spring.datasource.password=FMIdTt5B449yfy7zr5QTTZHWwJ2hv7Y0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}